substitutions:
  device_name: "smart-garden"
  friendly_name: "Smart Garden"
  project_name: "smart-garden"
  project_version: "1.0"
  ap_ssid: "Smart-Garden"
  ap_pwd: "smartgarden"

esphome:
  name: "${device_name}"
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Enable Over The Air updates
ota:

#Public location of this yaml file
dashboard_import:
  package_import_url: github://JGAguado/Smart_Garden/docs/source/files/configuration.yaml
  import_full_config: false

# Enable fallback hotspot (captive portal) in case wifi connection fails
captive_portal:

esp32_improv:
  authorizer: none

improv_serial:

wifi:
  ap:
    ssid: "${ap_ssid}"
    password: "${ap_pwd}"

# These relays will automatically turn off after 2 minutes
switch:
  - platform: gpio
    pin: 16
    id: relay_1
    name: "Zone 1"
    icon: "mdi:sprinkler-variant"
    on_turn_on:
    - delay: 120s
    - switch.turn_off: relay_1    
    
  - platform: gpio
    pin: 17
    id: relay_2
    name: "Zone 2"
    icon: "mdi:sprinkler-variant"
    on_turn_on:
      - delay: 120s
      - switch.turn_off: relay_2
    
  - platform: gpio
    pin: 18
    id: relay_3
    name: "Zone 3"
    icon: "mdi:sprinkler-variant"
    on_turn_on:
      - delay: 120s
      - switch.turn_off: relay_3      
    
  - platform: gpio
    pin: 19
    id: relay_4
    name: "Zone 4"
    icon: "mdi:sprinkler-variant"
    on_turn_on:
      - delay: 120s
      - switch.turn_off: relay_4  

sensor:
  - platform: adc
    pin: A4
    name: "VCC"
    update_interval: 60s
    filters:
      - calibrate_linear:
          - 0 -> 0
          - 0.55 -> 5